package fr.alpha.model;
// Generated 11 févr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private Integer idcategorie;
     private String nom;
     private Set<Forfait> forfaits = new HashSet<Forfait>(0);
     private Set<Modele> modeles = new HashSet<Modele>(0);

    public Categorie() {
    }

	
    public Categorie(String nom) {
        this.nom = nom;
    }
    public Categorie(String nom, Set<Forfait> forfaits, Set<Modele> modeles) {
       this.nom = nom;
       this.forfaits = forfaits;
       this.modeles = modeles;
    }
   
    public Integer getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(Integer idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set<Forfait> getForfaits() {
        return this.forfaits;
    }
    
    public void setForfaits(Set<Forfait> forfaits) {
        this.forfaits = forfaits;
    }
    public Set<Modele> getModeles() {
        return this.modeles;
    }
    
    public void setModeles(Set<Modele> modeles) {
        this.modeles = modeles;
    }




}


