package fr.alpha.model;
// Generated 11 f�vr. 2015 15:14:00 by Hibernate Tools 4.3.1



/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private Integer idforfait;
     private Categorie categorie;
     private String typePanne;
     private int coutPort;
     private int coutDevis;
     private int coutReparation;
     private int idcategorie;

    public Forfait() {
    }

    public Forfait(Categorie categorie, String typePanne, int coutPort, int coutDevis, int coutReparation, int idcategorie) {
       this.categorie = categorie;
       this.typePanne = typePanne;
       this.coutPort = coutPort;
       this.coutDevis = coutDevis;
       this.coutReparation = coutReparation;
       this.idcategorie = idcategorie;
    }
   
    public Integer getIdforfait() {
        return this.idforfait;
    }
    
    public void setIdforfait(Integer idforfait) {
        this.idforfait = idforfait;
    }
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }
    public String getTypePanne() {
        return this.typePanne;
    }
    
    public void setTypePanne(String typePanne) {
        this.typePanne = typePanne;
    }
    public int getCoutPort() {
        return this.coutPort;
    }
    
    public void setCoutPort(int coutPort) {
        this.coutPort = coutPort;
    }
    public int getCoutDevis() {
        return this.coutDevis;
    }
    
    public void setCoutDevis(int coutDevis) {
        this.coutDevis = coutDevis;
    }
    public int getCoutReparation() {
        return this.coutReparation;
    }
    
    public void setCoutReparation(int coutReparation) {
        this.coutReparation = coutReparation;
    }
    public int getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(int idcategorie) {
        this.idcategorie = idcategorie;
    }
    
    public int getTotal() {
        return coutDevis + coutPort + coutReparation;
    }




}


