package fr.alpha.model;
// Generated 11 f�vr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Garantie generated by hbm2java
 */
public class Garantie  implements java.io.Serializable {


     private Integer idgarantie;
     private int idmodele;
     private float prix;
     private int duree;
     private Set<Vendeur> vendeurs = new HashSet<Vendeur>(0);
     private Set<UtilisateurHasGarantie> utilisateurHasGaranties = new HashSet<UtilisateurHasGarantie>(0);

    public Garantie() {
    }

	
    public Garantie(int idmodele, float prix, int duree) {
        this.idmodele = idmodele;
        this.prix = prix;
        this.duree = duree;
    }
    public Garantie(int idmodele, float prix, int duree, Set<Vendeur> vendeurs, Set<UtilisateurHasGarantie> utilisateurHasGaranties) {
       this.idmodele = idmodele;
       this.prix = prix;
       this.duree = duree;
       this.vendeurs = vendeurs;
       this.utilisateurHasGaranties = utilisateurHasGaranties;
    }
   
    public Integer getIdgarantie() {
        return this.idgarantie;
    }
    
    public void setIdgarantie(Integer idgarantie) {
        this.idgarantie = idgarantie;
    }
    public int getIdmodele() {
        return this.idmodele;
    }
    
    public void setIdmodele(int idmodele) {
        this.idmodele = idmodele;
    }
    public float getPrix() {
        return this.prix;
    }
    
    public void setPrix(float prix) {
        this.prix = prix;
    }
    public int getDuree() {
        return this.duree;
    }
    
    public void setDuree(int duree) {
        this.duree = duree;
    }
    public Set<Vendeur> getVendeurs() {
        return this.vendeurs;
    }
    
    public void setVendeurs(Set<Vendeur> vendeurs) {
        this.vendeurs = vendeurs;
    }
    public Set<UtilisateurHasGarantie> getUtilisateurHasGaranties() {
        return this.utilisateurHasGaranties;
    }
    
    public void setUtilisateurHasGaranties(Set<UtilisateurHasGarantie> utilisateurHasGaranties) {
        this.utilisateurHasGaranties = utilisateurHasGaranties;
    }

    public String getDureeFormatee(){
        return duree + " mois : " + prix + "€";
    }


}


