package fr.alpha.model;
// Generated 11 févr. 2015 15:14:00 by Hibernate Tools 4.3.1



/**
 * InfosReparation generated by hbm2java
 */
public class InfosReparation  implements java.io.Serializable {


     private Integer idinfosReparation;
     private Produit produit;
     private String adresse;
     private String descritpion;
     private int idproduit;
     private int idutilisateur;
     private String etat;

    public InfosReparation() {
    }

    public InfosReparation(Produit produit, String adresse, String descritpion, int idproduit, int idutilisateur, String etat) {
       this.produit = produit;
       this.adresse = adresse;
       this.descritpion = descritpion;
       this.idproduit = idproduit;
       this.idutilisateur = idutilisateur;
       this.etat = etat;
    }
   
    public Integer getIdinfosReparation() {
        return this.idinfosReparation;
    }
    
    public void setIdinfosReparation(Integer idinfosReparation) {
        this.idinfosReparation = idinfosReparation;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getDescritpion() {
        return this.descritpion;
    }
    
    public void setDescritpion(String descritpion) {
        this.descritpion = descritpion;
    }
    public int getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(int idproduit) {
        this.idproduit = idproduit;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


