package fr.alpha.model;
// Generated 11 févr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private Integer idproduit;
     private Modele modele;
     private Utilisateur utilisateur;
     private int idUtilisateur;
     private int idModele;
     private Set<InfosReparation> infosReparations = new HashSet<InfosReparation>(0);

    public Produit() {
    }

	
    public Produit(Modele modele, Utilisateur utilisateur, int idUtilisateur, int idModele) {
        this.modele = modele;
        this.utilisateur = utilisateur;
        this.idUtilisateur = idUtilisateur;
        this.idModele = idModele;
    }
    public Produit(Modele modele, Utilisateur utilisateur, int idUtilisateur, int idModele, Set<InfosReparation> infosReparations) {
       this.modele = modele;
       this.utilisateur = utilisateur;
       this.idUtilisateur = idUtilisateur;
       this.idModele = idModele;
       this.infosReparations = infosReparations;
    }
   
    public Integer getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(Integer idproduit) {
        this.idproduit = idproduit;
    }
    public Modele getModele() {
        return this.modele;
    }
    
    public void setModele(Modele modele) {
        this.modele = modele;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public int getIdModele() {
        return this.idModele;
    }
    
    public void setIdModele(int idModele) {
        this.idModele = idModele;
    }
    public Set<InfosReparation> getInfosReparations() {
        return this.infosReparations;
    }
    
    public void setInfosReparations(Set<InfosReparation> infosReparations) {
        this.infosReparations = infosReparations;
    }




}


