package fr.alpha.model;
// Generated 11 févr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reparateur generated by hbm2java
 */
public class Reparateur  implements java.io.Serializable {


     private Integer idreparateur;
     private int zone;
     private String nom;
     private Set<Marque> marques = new HashSet<Marque>(0);

    public Reparateur() {
    }

	
    public Reparateur(int zone, String nom) {
        this.zone = zone;
        this.nom = nom;
    }
    public Reparateur(int zone, String nom, Set<Marque> marques) {
       this.zone = zone;
       this.nom = nom;
       this.marques = marques;
    }
   
    public Integer getIdreparateur() {
        return this.idreparateur;
    }
    
    public void setIdreparateur(Integer idreparateur) {
        this.idreparateur = idreparateur;
    }
    public int getZone() {
        return this.zone;
    }
    
    public void setZone(int zone) {
        this.zone = zone;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set<Marque> getMarques() {
        return this.marques;
    }
    
    public void setMarques(Set<Marque> marques) {
        this.marques = marques;
    }




}


