package fr.alpha.model;
// Generated 11 f�vr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UtilisateurHasGarantie generated by hbm2java
 */
public class UtilisateurHasGarantie  implements java.io.Serializable {


     private UtilisateurHasGarantieId id;
     private Garantie garantie;
     private Utilisateur utilisateur;
     private Date dateDebut;

    public UtilisateurHasGarantie() {
    }

    public UtilisateurHasGarantie(UtilisateurHasGarantieId id, Garantie garantie, Utilisateur utilisateur, Date dateDebut) {
       this.id = id;
       this.garantie = garantie;
       this.utilisateur = utilisateur;
       this.dateDebut = dateDebut;
    }
   
    public UtilisateurHasGarantieId getId() {
        return this.id;
    }
    
    public void setId(UtilisateurHasGarantieId id) {
        this.id = id;
    }
    public Garantie getGarantie() {
        return this.garantie;
    }
    
    public void setGarantie(Garantie garantie) {
        this.garantie = garantie;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }




}


