package fr.alpha.model;
// Generated 11 f�vr. 2015 15:14:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

    private Integer idutilisateur;
    private String nom;
    private String prenom;
    private String mail;
    private int adresse;
    private Set<UtilisateurHasGarantie> utilisateurHasGaranties = new HashSet<UtilisateurHasGarantie>(0);
    private Set<Produit> produits = new HashSet<Produit>(0);
    private String Mdp;

    public Utilisateur() {
    }

    public Utilisateur(String nom, String prenom, String mail, int adresse, String Mdp) {
        this.nom = nom;
        this.prenom = prenom;
        this.mail = mail;
        this.adresse = adresse;
        this.Mdp = Mdp;
    }

    public Utilisateur(String nom, String prenom, String mail, int adresse, Set<UtilisateurHasGarantie> utilisateurHasGaranties, Set<Produit> produits, String Mdp) {
        this.nom = nom;
        this.prenom = prenom;
        this.mail = mail;
        this.adresse = adresse;
        this.utilisateurHasGaranties = utilisateurHasGaranties;
        this.produits = produits;
        this.Mdp = Mdp;
    }

    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public int getAdresse() {
        return this.adresse;
    }

    public void setAdresse(int adresse) {
        this.adresse = adresse;
    }

    public Set<UtilisateurHasGarantie> getUtilisateurHasGaranties() {
        return this.utilisateurHasGaranties;
    }

    public void setUtilisateurHasGaranties(Set<UtilisateurHasGarantie> utilisateurHasGaranties) {
        this.utilisateurHasGaranties = utilisateurHasGaranties;
    }

    public Set<Produit> getProduits() {
        return this.produits;
    }

    public void setProduits(Set<Produit> produits) {
        this.produits = produits;
    }

    public String getMdp() {
        return Mdp;
    }

    public void setMdp(String Mdp) {
        this.Mdp = Mdp;
    }

}
