package fr.alpha.model;
// Generated 11 févr. 2015 15:14:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendeur generated by hbm2java
 */
public class Vendeur  implements java.io.Serializable {


     private Integer idvendeur;
     private String nomEntreprise;
     private String nomVendeur;
     private Date dernierPaiement;
     private float ardoise;
     private float pourcentage;
     private Set<Garantie> garanties = new HashSet<Garantie>(0);

    public Vendeur() {
    }

	
    public Vendeur(String nomEntreprise, String nomVendeur, Date dernierPaiement, float ardoise, float pourcentage) {
        this.nomEntreprise = nomEntreprise;
        this.nomVendeur = nomVendeur;
        this.dernierPaiement = dernierPaiement;
        this.ardoise = ardoise;
        this.pourcentage = pourcentage;
    }
    public Vendeur(String nomEntreprise, String nomVendeur, Date dernierPaiement, float ardoise, float pourcentage, Set<Garantie> garanties) {
       this.nomEntreprise = nomEntreprise;
       this.nomVendeur = nomVendeur;
       this.dernierPaiement = dernierPaiement;
       this.ardoise = ardoise;
       this.pourcentage = pourcentage;
       this.garanties = garanties;
    }
   
    public Integer getIdvendeur() {
        return this.idvendeur;
    }
    
    public void setIdvendeur(Integer idvendeur) {
        this.idvendeur = idvendeur;
    }
    public String getNomEntreprise() {
        return this.nomEntreprise;
    }
    
    public void setNomEntreprise(String nomEntreprise) {
        this.nomEntreprise = nomEntreprise;
    }
    public String getNomVendeur() {
        return this.nomVendeur;
    }
    
    public void setNomVendeur(String nomVendeur) {
        this.nomVendeur = nomVendeur;
    }
    public Date getDernierPaiement() {
        return this.dernierPaiement;
    }
    
    public void setDernierPaiement(Date dernierPaiement) {
        this.dernierPaiement = dernierPaiement;
    }
    public float getArdoise() {
        return this.ardoise;
    }
    
    public void setArdoise(float ardoise) {
        this.ardoise = ardoise;
    }
    public float getPourcentage() {
        return this.pourcentage;
    }
    
    public void setPourcentage(float pourcentage) {
        this.pourcentage = pourcentage;
    }
    public Set<Garantie> getGaranties() {
        return this.garanties;
    }
    
    public void setGaranties(Set<Garantie> garanties) {
        this.garanties = garanties;
    }




}


